version: "3.4"
services:
  react-client:
    image: react-client
    stdin_open: true
    ports:
      - "3000:3000"

  app-server:
    image: app-server
    ports:
      - "5000:5000"
    depends_on: 
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
      